name = "SkyFactory Remake"
author = "KlutzyBubbles"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b2d89844407f63ac53711e690d42cc245a4ec7da75b1d8e69f70466f6d805a7"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4", "1.16.5"]
